/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "gap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GAPPingReq, GAPPingReq, AUTO)


PB_BIND(GAPPingResp, GAPPingResp, AUTO)


PB_BIND(GAPSetLogVerbosityReq, GAPSetLogVerbosityReq, AUTO)


PB_BIND(GAPSetLogVerbosityResp, GAPSetLogVerbosityResp, AUTO)


PB_BIND(GAPSetGyroscopeReq, GAPSetGyroscopeReq, AUTO)


PB_BIND(GAPSetGyroscopeResp, GAPSetGyroscopeResp, AUTO)


PB_BIND(GAPSetVersionReq, GAPSetVersionReq, AUTO)


PB_BIND(GAPSetVersionResp, GAPSetVersionResp, AUTO)


PB_BIND(GAPGetVersionReq, GAPGetVersionReq, AUTO)


PB_BIND(GAPGetVersionResp, GAPGetVersionResp, AUTO)


PB_BIND(GAPSelftestReq, GAPSelftestReq, AUTO)


PB_BIND(GAPSelftestResp, GAPSelftestResp, AUTO)


PB_BIND(GAPPowerSaveModeReq, GAPPowerSaveModeReq, AUTO)


PB_BIND(GAPPowerSaveModeResp, GAPPowerSaveModeResp, AUTO)






